import { useEffect, useRef, useState } from 'react'
import { App as CapacitorApp } from '@capacitor/app'
import { Layout } from './components/Layout'
import Menu, { type BotNames } from './components/Menu/Menu'
import Gameplay from './components/Gameplay/Gameplay'
import Result from './components/Result/Result'
import OnlineLobby from './components/Online/OnlineLobby'
import OnlineGameplay from './components/Online/OnlineGameplay'
import { useGameStore } from './store/gameStore'
import { useOnlineStore } from './online/onlineStore'
import type { AIDifficulty } from './engine/ai'

const DEFAULT_BOT_NAMES: BotNames = {
  partner: 'Bruno',
  opponent1: 'Ana',
  opponent2: 'Carlos',
}

type Screen = 'menu' | 'gameplay' | 'result' | 'onlineLobby' | 'onlineGameplay'

/** True when the page was opened via a room-invite link (`?sala=CODE`),
 * generated by the QR code / join link in OnlineLobby so a scan lands
 * straight in the online join flow instead of the main menu. */
function hasRoomInviteParam(): boolean {
  return new URLSearchParams(window.location.search).has('sala')
}

export default function App() {
  const [screen, setScreen] = useState<Screen>(() => (hasRoomInviteParam() ? 'onlineLobby' : 'menu'))
  // Remembered so "Nova Partida" from the Result screen can restart with
  // the same settings without having to dig them out of the (reset) game
  // instance. Menu.onStart reports what the player picked before starting.
  const [lastDifficulty, setLastDifficulty] = useState<AIDifficulty>('medium')
  const [lastPlayerName, setLastPlayerName] = useState('Você')
  const [lastBotNames, setLastBotNames] = useState<BotNames>(DEFAULT_BOT_NAMES)

  const game = useGameStore(s => s.game)
  // `version` selected alongside `game` per the store's reactivity contract:
  // `game` keeps a stable reference across mutations, so App must still
  // subscribe to `version` to re-render when e.g. the game finishes.
  const version = useGameStore(s => s.version)
  void version

  const handleStart = (difficulty: AIDifficulty, playerName: string, names: BotNames) => {
    setLastDifficulty(difficulty)
    setLastPlayerName(playerName)
    setLastBotNames(names)
    setScreen('gameplay')
  }

  // Match just ended (matchWinner set) -> start a brand-new match with the
  // same settings. `initGame` also resets matchScores/matchCanastras/round.
  const handleNewMatch = () => {
    useGameStore.getState().initGame(lastPlayerName, lastDifficulty, lastBotNames)
    setScreen('gameplay')
  }

  // Match still in progress -> advance to the next round, keeping the
  // accumulated matchScores/matchCanastras.
  const handleNextRound = () => {
    useGameStore.getState().startNextRound()
    setScreen('gameplay')
  }

  const handleBackToMenu = () => {
    useGameStore.getState().resetGame()
    setScreen('menu')
  }

  // A sala foi fechada à força (hoje só "o anfitrião saiu" - ver
  // server/protocol.ts handleClose) - o onlineStore já fez a limpeza da
  // conexão sozinho (ver o case 'roomClosed' em onlineStore.ts); só falta
  // avisar quem ainda estava lá e tirá-lo da tela online, já que a sala
  // não existe mais (pedido do usuário: "a sala deve cair junto... um
  // aviso na tela dos outros jogadores").
  const roomClosedReason = useOnlineStore(s => s.roomClosedReason)
  useEffect(() => {
    if (!roomClosedReason) return
    void import('./online/nativeHostServer').then(({ stopNativeHost }) => stopNativeHost())
    window.alert(roomClosedReason)
    useOnlineStore.getState().clearRoomClosedReason()
    setScreen('menu')
  }, [roomClosedReason])

  const handleOnlineBackToMenu = () => {
    // No-op se este aparelho não estava hospedando (ver stopNativeHost em
    // nativeHostServer.ts) - sempre seguro chamar, mesmo quem só entrou
    // como convidado na sala de outra pessoa.
    void import('./online/nativeHostServer').then(({ stopNativeHost }) => stopNativeHost())
    useOnlineStore.getState().leave()
    setScreen('menu')
  }

  /** Sai de uma partida OFFLINE em andamento (com confirmação, já que
   * abandona a rodada em curso) — usado tanto pelo botão na tela
   * (ExitButton, dentro de Gameplay.tsx) quanto pelo voltar de hardware do
   * Android (ver o listener abaixo), pra garantir o MESMO comportamento
   * pelos dois caminhos. */
  const handleExitGameplay = () => {
    if (window.confirm('Sair da partida em andamento? Seu progresso desta rodada será perdido.')) {
      handleBackToMenu()
    }
  }

  /** Mesma ideia de handleExitGameplay, só que pro modo ONLINE — chamado
   * pelo ExitButton dentro de OnlineGameplay.tsx. */
  const handleExitOnlineGameplay = () => {
    if (window.confirm('Sair da partida em andamento? Você será desconectado dos outros jogadores.')) {
      handleOnlineBackToMenu()
    }
  }

  // Botão voltar de hardware do Android: sem este listener, o padrão do
  // WebView é MINIMIZAR O APP INTEIRO em qualquer tela, já que este é um
  // SPA de tela única sem histórico de navegação real pro WebView voltar -
  // era assim em toda tela, offline e online, mesmo no meio de uma partida
  // (relato do usuário: "em momento nenhum tem um botão de voltar"). Mapeia
  // CADA tela pra uma ação sensata, com a MESMA confirmação que o botão na
  // tela usa nos casos que abandonam algo em andamento.
  //
  // `screenRef` existe porque o listener é registrado UMA VEZ (o efeito
  // roda só na montagem) - sem o ref, o closure capturaria o `screen` da
  // primeira renderização pra sempre.
  const screenRef = useRef(screen)
  screenRef.current = screen
  useEffect(() => {
    const sub = CapacitorApp.addListener('backButton', () => {
      switch (screenRef.current) {
        case 'menu':
          void CapacitorApp.exitApp()
          break
        case 'gameplay':
          handleExitGameplay()
          break
        case 'result':
          // Nada a perder aqui (a rodada já terminou) - mesmo destino do
          // "Voltar ao Menu" que a tela já mostra, sem confirmação.
          handleBackToMenu()
          break
        case 'onlineLobby':
          // Ainda escolhendo criar/entrar (nenhuma sala envolvida) -> vai
          // direto pro menu. Já dentro de uma sala (esperando ou jogando)
          // -> confirma antes de sair e desconectar.
          if (useOnlineStore.getState().code === null) {
            setScreen('menu')
          } else if (window.confirm('Sair da sala?')) {
            handleOnlineBackToMenu()
          }
          break
        case 'onlineGameplay':
          // A rodada já terminou e o placar está na tela (OnlineResult,
          // dentro de OnlineGameplay) -> nada a perder, sem confirmação.
          // Partida ainda em andamento -> mesma confirmação do ExitButton.
          if (useOnlineStore.getState().view?.status === 'finished') {
            handleOnlineBackToMenu()
          } else {
            handleExitOnlineGameplay()
          }
          break
      }
    })
    return () => {
      void sub.then(handle => handle.remove())
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- listener registrado uma vez só; screenRef sempre traz o valor atual
  }, [])

  const fitScreen =
    screen === 'gameplay' ||
    screen === 'onlineGameplay' ||
    screen === 'menu' ||
    screen === 'result' ||
    screen === 'onlineLobby'

  return (
    <Layout fit={fitScreen}>
      {screen === 'menu' && (
        <Menu onStart={handleStart} onPlayOnline={() => setScreen('onlineLobby')} />
      )}
      {screen === 'gameplay' && game && (
        <Gameplay onGameEnd={() => setScreen('result')} onExit={handleExitGameplay} />
      )}
      {screen === 'result' && game && (
        <Result onBackToMenu={handleBackToMenu} onNextRound={handleNextRound} onNewMatch={handleNewMatch} />
      )}
      {screen === 'onlineLobby' && (
        <OnlineLobby
          onBackToMenu={handleOnlineBackToMenu}
          onGameStart={() => setScreen('onlineGameplay')}
        />
      )}
      {screen === 'onlineGameplay' && <OnlineGameplay onBackToMenu={handleOnlineBackToMenu} />}
    </Layout>
  )
}
