import { useState } from 'react'
import { Layout } from './components/Layout'
import Menu, { type BotNames } from './components/Menu/Menu'
import Gameplay from './components/Gameplay/Gameplay'
import Result from './components/Result/Result'
import OnlineLobby from './components/Online/OnlineLobby'
import OnlineGameplay from './components/Online/OnlineGameplay'
import { useGameStore } from './store/gameStore'
import { useOnlineStore } from './online/onlineStore'
import type { AIDifficulty } from './engine/ai'

const DEFAULT_BOT_NAMES: BotNames = {
  partner: 'Parceiro',
  opponent1: 'Adversário 1',
  opponent2: 'Adversário 2',
}

type Screen = 'menu' | 'gameplay' | 'result' | 'onlineLobby' | 'onlineGameplay'

/** True when the page was opened via a room-invite link (`?sala=CODE`),
 * generated by the QR code / join link in OnlineLobby so a scan lands
 * straight in the online join flow instead of the main menu. */
function hasRoomInviteParam(): boolean {
  return new URLSearchParams(window.location.search).has('sala')
}

export default function App() {
  const [screen, setScreen] = useState<Screen>(() => (hasRoomInviteParam() ? 'onlineLobby' : 'menu'))
  // Remembered so "Nova Partida" from the Result screen can restart with
  // the same settings without having to dig them out of the (reset) game
  // instance. Menu.onStart reports what the player picked before starting.
  const [lastDifficulty, setLastDifficulty] = useState<AIDifficulty>('medium')
  const [lastPlayerName, setLastPlayerName] = useState('Você')
  const [lastBotNames, setLastBotNames] = useState<BotNames>(DEFAULT_BOT_NAMES)

  const game = useGameStore(s => s.game)
  // `version` selected alongside `game` per the store's reactivity contract:
  // `game` keeps a stable reference across mutations, so App must still
  // subscribe to `version` to re-render when e.g. the game finishes.
  const version = useGameStore(s => s.version)
  void version

  const handleStart = (difficulty: AIDifficulty, playerName: string, names: BotNames) => {
    setLastDifficulty(difficulty)
    setLastPlayerName(playerName)
    setLastBotNames(names)
    setScreen('gameplay')
  }

  // Match just ended (matchWinner set) -> start a brand-new match with the
  // same settings. `initGame` also resets matchScores/matchCanastras/round.
  const handleNewMatch = () => {
    useGameStore.getState().initGame(lastPlayerName, lastDifficulty, lastBotNames)
    setScreen('gameplay')
  }

  // Match still in progress -> advance to the next round, keeping the
  // accumulated matchScores/matchCanastras.
  const handleNextRound = () => {
    useGameStore.getState().startNextRound()
    setScreen('gameplay')
  }

  const handleBackToMenu = () => {
    useGameStore.getState().resetGame()
    setScreen('menu')
  }

  const handleOnlineBackToMenu = () => {
    useOnlineStore.getState().leave()
    setScreen('menu')
  }

  const fitScreen = screen === 'gameplay' || screen === 'onlineGameplay'

  return (
    <Layout fit={fitScreen}>
      {screen === 'menu' && (
        <Menu onStart={handleStart} onPlayOnline={() => setScreen('onlineLobby')} />
      )}
      {screen === 'gameplay' && game && <Gameplay onGameEnd={() => setScreen('result')} />}
      {screen === 'result' && game && (
        <Result onBackToMenu={handleBackToMenu} onNextRound={handleNextRound} onNewMatch={handleNewMatch} />
      )}
      {screen === 'onlineLobby' && (
        <OnlineLobby
          onBackToMenu={handleOnlineBackToMenu}
          onGameStart={() => setScreen('onlineGameplay')}
        />
      )}
      {screen === 'onlineGameplay' && <OnlineGameplay onBackToMenu={handleOnlineBackToMenu} />}
    </Layout>
  )
}
